[package]
name = "clone_dyn_meta"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/clone_dyn_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/clone_dyn_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/clone_dyn_meta"
description = """
Derive to clone dyn structures.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/derive/clone_dyn_meta",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = []
full = []

[lib]
proc-macro = true
name = "clone_dyn_meta"
path = "src/derive/clone_dyn_meta/clone_dyn_meta_lib.rs"

[[test]]
name = "clone_dyn_meta_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[dependencies]
proc_macro_tools = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
