[package]
name = "wtools_smoke"
version = "0.0.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools_smoke"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools_smoke"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools_smoke"
description = """
Module-wrapper for smoke testing.
"""
keywords = [ "testing", "smoke" ]

include = [
  "/src/lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtools_smoke"
path = "src/lib.rs"

[[test]]
name = "wtools_smoke_local_test"
path = "test/local_test.rs"

[[test]]
name = "wtools_smoke_published_test"
path = "test/published_test.rs"

[dependencies]
wtools_local = { version = "*", path = "../../rust/wtools", package = "wtools" }
wtools_published = { version = "*", package = "wtools" }
