[package]
name = "willbe_a"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/template_blank"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/template_blank"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/template_blank"
description = """
A
"""
categories = [ ]
keywords = [ ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = []
use_alloc = []
enabled = []

[dependencies]

[dev-dependencies]
test_tools = { workspace = true }
