[package]
name = "procedural_macro_runtime"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/procedural_macro_runtime"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/procedural_macro_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/procedural_macro_runtime"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta/procedural_macro_runtime_lib.rs",
  "/rust/impl/meta/procedural_macro/runtime",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "procedural_macro_runtime"
path = "src/meta/procedural_macro/runtime/procedural_macro_lib.rs"

[[test]]
name = "procedural_macro_runtime_test"
path = "tests/meta/procedural_macro_runtime_tests.rs"

[[test]]
name = "procedural_macro_runtime_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[dependencies]

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
