[package]
name = "integration_test"
version = "0.0.1"
publish = false
edition = "2021"
description = """
Integration test.
"""

[dependencies]

local = { version = "*", path = "../../rust/wtools", package = "wtools" }

published = { version = "*", package = "wtools" }
