[package]
name = "wtools_sample_trivial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wtools = ""
# wtools = { path = "../../../out/rust.wtools" }
