[package]
name = "fundamental_data_type"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/fundamental_data_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/fundamental_data_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/fundamental_data_type"
description = """
Fundamental data types and type constructors, like Single, Pair, Many.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/dt/fundamental_data_type",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "fundamental_data_type"
path = "rust/impl/dt/fundamental_data_type/lib.rs"

[[test]]
name = "fundamental_data_type_test"
path = "rust/test/dt/fundamental_data_type/lib_test.rs"

[[example]]
name = "fundamental_data_type_trivial_sample"
path = "sample/rust/fundamental_data_type_trivial_sample/src/main.rs"

[[example]]
name = "fundamental_data_type_derive_and_attr_sample"
path = "sample/rust/fundamental_data_type_derive_and_attr_sample/src/main.rs"

[[example]]
name = "fundamental_data_type_struct_sample"
path = "sample/rust/fundamental_data_type_struct_sample/src/main.rs"

[[example]]
name = "fundamental_data_type_parametrized_element_sample"
path = "sample/rust/fundamental_data_type_parametrized_element_sample/src/main.rs"

[[example]]
name = "fundamental_data_type_parametrized_tuple_sample"
path = "sample/rust/fundamental_data_type_parametrized_tuple_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# trybuild = { version = "~1.0", features = [ "diff" ] }
