[package]
name = "former_derive"
version = "0.1.6"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former_derive"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_derive"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_derive"
description = """
Former - a variation of builder pattern. Implementation of its derive macro. Should not be used independently, instead use module::former which relies on the module.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/former/derive",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
proc-macro = true
name = "former_derive"
path = "rust/impl/former/derive/mod.rs"

[dependencies]
# proc-macro-error = "~1.0.4"
proc-macro2 = "~1.0.32"
quote = "~1.0.10"
syn = { version = "~1.0.81", features = ["full", "extra-traits", "parsing"] }
unzip-n = "~0.1.2"
werror = { path = "../werror", version = "~0.0" }
wproc_macro = { path = "../wproc_macro", version = "~0.0" }

[dev-dependencies]
trybuild = { version = "~1.0", features = ["diff"] }
