[package]
name = "sketch_blank"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/sketch_blank"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/sketch_blank"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/sketch_blank"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/sketch_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "sketch_blank"
path = "rust/impl/sketch_blank/sketch_blank_lib.rs"

[[test]]
name = "sketch_blank_test"
path = "rust/test/sketch_blank/sketch_blank_lib_test.rs"

# [[example]]
# name = "sketch_blank_trivial_sample"
# path = "sample/rust/sketch_blank_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
