[package]
name = "____blank"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/___"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/sketch_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "sketch_blank"
path = "rust/impl/sketch_blank/lib.rs"

[[test]]
name = "sketch_blank_test"
path = "rust/test/sketch_blank/lib_test.rs"

# [[example]]
# name = "____trivial"
# path = "sample/rust/____trivial/src/main.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }
