
tasks:
  - init: |
      cargo build --manifest-path module/rust/wtools/Cargo.toml
    command: |
      cargo build --manifest-path module/rust/wtools/Cargo.toml

vscode:
  extensions:
    - matklad.rust-analyzer
