
checkoutLocation : "."
workspaceLocation : "."

tasks :
  - init : |
      cargo build --manifest-path module/rust/wtools/Cargo.toml
      cargo run --example wtools_trivial_sample
    command : |
      # cargo run --example wtools_trivial_sample
      # cargo run --example # list examples
      echo $SAMPLE_PATH

vscode :
  extensions :
    - matklad.rust-analyzer

github :
  prebuilds :
    addBadge : true
    pullRequests : true