
checkoutLocation : "."
workspaceLocation : "."

tasks :
  - init : |
      cd $RUN_PATH
      cargo build
      cargo run $RUN_POSTFIX
    command : |
      # list examples
      if [[ "${HAS_SAMPLES}" == "true" ]] || [[ "${HAS_SAMPLES}" == "1" ]]; then cargo run --example; fi
      echo $RUN_PATH

vscode :
  extensions :
    - matklad.rust-analyzer

github :
  prebuilds :
    addBadge : true
    pullRequests : true
