
path :

  in : '.'
  out : 'out'
  temp : 'path::out'
  proto : './proto'
  doc : './doc'

  out.raw.debug :
    path : '{path::out}/debug'
    criterion :
      debug : debug
      raw : raw
      tests : 'no.tests'
      content : prime
  out.compiled.debug :
    path : '{path::out}/compiled.debug'
    criterion :
      debug : debug
      raw : compiled
      tests : 'no.tests'
      content : prime
  out.raw.release :
    path : '{path::out}/raw.release'
    criterion :
      debug : release
      raw : raw
      tests : 'no.tests'
      content : prime
  out.compiled.release :
    path : '{path::out}/release'
    criterion :
      debug : release
      raw : compiled
      tests : 'no.tests'
      content : prime
  out.tests.raw.debug :
    path : '{path::out}/tests.raw.debug'
    criterion :
      debug : debug
      raw : raw
      tests : 'only.tests'
      content : prime
  out.tests.compiled.debug :
    path : '{path::out}/tests.compiled.debug'
    criterion :
      debug : debug
      raw : compiled
      tests : 'only.tests'
      content : prime
  out.tests.raw.release :
    path : '{path::out}/tests.raw.release'
    criterion :
      debug : release
      raw : raw
      tests : 'only.tests'
      content : prime
  out.tests.compiled.release :
    path : '{path::out}/tests.compiled.release'
    criterion :
      debug : release
      raw : compiled
      tests : 'only.tests'
      content : prime

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      content : prime
    filePath :
      path::proto : path::out.*=1

  transpile.proto.raw :
    inherit : predefined.*
    step : files.transpile
    criterion :
      raw : raw
      debug : release
      content : prime
    filePath :
      path::proto : '{path::out.raw.release}'

  transpile.proto.no.tests.compiled :
    inherit : predefined.*
    step : files.transpile
    criterion :
      tests : 'no.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : '{path::out.*=1}/Main.s'

  transpile.proto.only.tests.compiled :
    step : files.transpile
    inherit : predefined.*
    criterion :
      tests : 'only.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 1
      path::proto : '{path::out.*=1}/Tests.s'

step :

  clean.out :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      tests : [ 'no.tests', 'only.tests' ]
      content : [ 'prime', 'npm' ]

  clean.out.npm :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : debug
      raw : compiled
      tests : no.tests
      content : npm

build :

  debug :
    criterion :
      default : 1
      debug : debug
      raw : raw
      content : prime
    steps :
      - timelapse.begin
      - step::clean.out*=2
      - reflect.proto.*=1
      - timelapse.end

  compiled.debug :
    criterion :
      debug : debug
      raw : compiled
      content : prime
    steps :
      - timelapse.begin
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
      - timelapse.end

  raw.release :
    criterion :
      debug : release
      raw : raw
      content : prime
    steps :
      - timelapse.begin
      - step::clean.out*=2
      - transpile.proto.raw
      - timelapse.end

  release :
    criterion :
      debug : release
      raw : compiled
      content : prime
    steps :
      - timelapse.begin
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
      - timelapse.end

  npm :
    criterion :
      default : 1
      debug : debug
      raw : compiled
      content : npm
    steps :
      # - step::clean.out.npm*=1
      - npm.generate

  all :
    steps :
      - build::debug
      - build::compiled.debug
      - build::raw.release
      - build::release
      - build::npm
