[package]
name = "wtools"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Wandalen <wanalen@01.school>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools"
repository = "https://github.com/Wandalen/wTools/tree/master/out/rust.wtools"
homepage = "https://github.com/Wandalen/wTools/tree/master/out/rust.wtools"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust",
  "/Cargo.toml",
  "/Readme.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wtools"
path = "rust/wtools/mod.rs"

[[test]]
name = "wtools_test"
path = "rust/test/mod.rs"

[dependencies]
regex = "1.5.4"
chrono = "0.4.19"
paste = "1.0.5"

[[example]]
name = "trivial"
path = "sample/rust/trivial/src/main.rs"
