[workspace]
resolver = "2"
members = [
  "module/rust/*",
  "sample/rust/*",
]
exclude = [
  "*",
  "module/rust/-*",
  "sample/rust/-*",
  "module/rust/_*",
  "sample/rust/_*",
]
# default-members = [ "module/rust/wtools" ]
