
[workspace]
resolver = "2"
members = [
  "module/rust/former_derive",
  "module/rust/former_runtime",
  "module/rust/former",
  "module/rust/all"
]
exclude = [
  "*",
  "out/rust/*",
  "out/rust/former_runtime",
  "out/rust/former_derive",
  "out/rust/former",
]
default-members = ["module/rust/all"]
