
[workspace]
resolver = "2"
members = [
  "module/rust/*",
  "sample/rust/*",
  # "module/rust/former_derive",
  # "module/rust/former_runtime",
  # "module/rust/former",
  # "module/rust/implements",
  # "module/rust/instance_of",
  # "module/rust/is_slice",
  # "module/rust/wtest",
  # "module/rust/wtools",
  # "sample/rust/former_trivial",
  # "sample/rust/is_slice_trivial",
  # "sample/rust/meta_implements_trivial",
  # "sample/rust/meta_instance_of_trivial",
  # "sample/rust/wtools_trivial",
  # "sample/rust/wtest_trivial",
]
exclude = [
  "*",
  "module/rust/-*",
  "sample/rust/-*",
  "module/rust/_*",
  "sample/rust/_*",
]
default-members = ["module/rust/wtools"]
