[workspace]
resolver = "2"
members = [
  "module/rust/*",
  "module/rust_alias/*",
  "module/rust_move/*",
  "module/rust_math/*",
  "sample/rust/*",
]
exclude = [
  "*",
  # "module/rust/-*",
  # "sample/rust/-*",
  # "module/rust/_*",
  # "sample/rust/_*",
  # "sample/rust/_select_matching",
]
# default-members = [ "module/rust/wtools" ]
