[package]
name = "wtools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wtools"
path = "rust/wtools/mod.rs"

[[test]]
name = "wtools-test"
path = "rust/test/common_list.rs"

[dependencies]
regex = "1.5.4"
chrono = "0.4.19"
