[package]
name = "wca"
version = "0.1.1"
edition = "2018"
authors = ["Kostiantyn Wandalen <wandalen@obox.systems>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wca"
repository = "https://github.com/Wandalen/wTools/tree/master/module/move/wca"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/move/wca/Readme.md"
description = """
The tool to make CLI ( commands user interface ). It is able to aggregate external binary applications, as well as functions, which are written in your language.
"""
categories = [ "command-line-interface", "command-line-utilities" ]
keywords = [ "wtools", "CLI", "CUI", "user-interface" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/ca",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]
use_std = []
use_alloc = []

[lib]
name = "wca"
path = "rust/impl/ca/wca_lib.rs"

[[test]]
name = "wca_test"
path = "rust/test/ca/wca_tests.rs"

[[test]]
name = "wca_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
former = { version = "~0.1", path = "../../rust/former" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
