[package]
name = "automata_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/template_blank"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/template_blank"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/template_blank"
description = """
Automata tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/_template_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "automata_tools"
path = "rust/impl/automata/automata_tools_lib.rs"

# [[test]]
# name = "automata_tools_test"
# path = "rust/test/automata/automata_lib_test.rs"

# [[example]]
# name = "automata_trivial_sample"
# path = "sample/rust/automata_trivial_sample/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools", features = [] }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }

