[package]
name = "former_derive"
version = "0.1.10"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former_derive"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/former_derive"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/former_derive"
description = """
This module was renamed. Please use module::former_meta.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
proc-macro = true
name = "former_derive"
path = "rust/impl/_blank/empty_lib.rs"

[dependencies]
# proc-macro2 = "~1.0"
# quote = "~1.0"
# heck = "~0.4"
# syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing", "printing" ] }
# iter_tools = { path = "../../rust/iter_tools", version = "~0.1" }
# werror = { path = "../../rust/werror", version = "~0.1" }
# former_meta = { version = "~0.1", path = "../../rust/former_meta" }
# proc_macro_tools = { version = "~0.1", path = "../../rust/proc_macro_tools" }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
