[package]
name = "fundamental_data_type_parametrized_tuple_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
type_constructor = { version = "*", path = "../../../module/rust/type_constructor" }
