[package]
name = "inspect_type"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/inspect_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/inspect_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/inspect_type"
description = """
Diagnostic-purpose tools to inspect type of a variable and its size.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "diagnostic-purpose" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

exclude = [ "/tests", "/examples", "-*" ]
include = [
  # "/rust/impl/typing/inspect_type_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
# use_std = []
no_std = []
use_alloc = []
enabled = []

nightly = []

[dependencies]

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
