[package]
name = "wtest_basic"
version = "0.0.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtest_basic"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest_basic"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest_basic"
description = """
Tools for writing tests. The most basic things.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

include = [
  "/rust/impl/test/basic.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtest_basic"
path = "rust/impl/test/basic.rs"

[[test]]
name = "wtest_basic_test"
path = "rust/test/test/mod.rs"

[[example]]
name = "trivial"
path = "sample/rust/wtest_basic_trivial/src/main.rs"

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }

[dependencies]
paste = "~1.0"
anyhow = "~1.0"
