[package]
name = "werror"
version = "0.0.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/werror"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/werror"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/werror"
description = """
Basic exceptions handling mechanism.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/error",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "werror"
path = "rust/impl/error/mod.rs"

[[test]]
name = "werror_test"
path = "rust/test/error/mod.rs"

[[example]]
name = "trivial"
path = "sample/rust/werror_trivial/src/main.rs"

[dependencies]

[dev-dependencies]
wtest_basic = { path = "../wtest_basic", version = "~0" }
