[package]
name = "type_constructor_derive_make_meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
name = "type_constructor_derive_make_meta"
path = "rust/impl/dt/type_constructor/derive/derive_make.rs"

[dependencies]
syn = { version = "1.0.101", features = [ "full" ] }
quote = "1.0"
proc-macro2 = "1.0"
