[package]
name = "wtest"
version = "0.0.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtest"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
description = """
Tools for writing and runnint tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

include = [
  "/rust/impl/test/mod.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtest"
path = "rust/impl/test/mod.rs"

[[test]]
name = "wtest_test"
path = "rust/test/test/wtest.rs"

[[example]]
name = "trivial"
path = "sample/rust/wtest_trivial/src/main.rs"

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }

[dependencies]
# paste = "~1.0"
# anyhow = "~1.0"
wtest_basic = { path = "../wtest_basic", version = "~0" }
