[package]
name = "std_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/std_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/std_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/std_tools"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/_template",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "std_tools"
path = "rust/impl/_template/lib.rs"

[[test]]
name = "template_alias_test"
path = "rust/test/_template/lib_test.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
