[package]
name = "wtools"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools"
repository = "https://github.com/wtools"
homepage = "https://github.com/wtools"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtools"
path = "rust/impl/mod.rs"

[[test]]
name = "wtools_test"
path = "rust/test/mod.rs"

[[example]]
name = "trivial"
path = "sample/rust/wtools_trivial/src/main.rs"

[[example]]
name = "meta_implements"
path = "sample/rust/meta_implements_trivial/src/main.rs"

[[example]]
name = "is_slice"
path = "sample/rust/is_slice_trivial/src/main.rs"

[[example]]
name = "wtest"
path = "sample/rust/wtest_trivial/src/main.rs"

[[example]]
name = "wtest_basic"
path = "sample/rust/wtest_basic_trivial/src/main.rs"

[dev-dependencies]
trybuild = { version = "1.0.52", features = ["diff"] }
maplit = "1.0.2"

[dependencies]
regex = "1.5.4"
chrono = "0.4.19"
paste = "1.0.5"
anyhow = "1.0.48"
former_derive = { path = "../former_derive", version = "~0" }
former_runtime = { path = "../former_runtime", version = "~0" }
inspect_type = { path = "../inspect_type", version = "~0" }
is_slice = { path = "../is_slice", version = "~0" }
implements = { path = "../implements", version = "~0" }
# instance_of = { path = "../instance_of", version = "~0" }
# wtest = { path = "../wtest", version = "~0" }
wtest_basic = { path = "../wtest_basic", version = "~0" }

[features]
all = []
default = ["all"]
