[package]
name = "wtools"
version = "0.1.6"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/mod.rs",
  "/rust/impl/meta/mod.rs",
  "/rust/impl/typing/mod.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtools"
path = "rust/impl/mod.rs"

[[test]]
name = "wtools_test"
path = "rust/test/mod.rs"

# [[example]]
# name = "former"
# path = "sample/rust/former_trivial/src/main.rs"
#
# [[example]]
# name = "implements"
# path = "sample/rust/implements_trivial/src/main.rs"
#
# [[example]]
# name = "inspect_type"
# path = "sample/rust/inspect_type_trivial/src/main.rs"
#
# [[example]]
# name = "is_slice"
# path = "sample/rust/is_slice_trivial/src/main.rs"
#
# [[example]]
# name = "wtest_basic"
# path = "sample/rust/wtest_basic_trivial/src/main.rs"

[[example]]
name = "wtools_trivial"
path = "sample/rust/wtools_trivial/src/main.rs"

[features]
with_wtools = []
with_proc_macro = [ "wproc_macro" ]
default = [ "with_wtools" ]

[dependencies]
former = { path = "../former", version = "~0" }
inspect_type = { path = "../inspect_type", version = "~0" }
is_slice = { path = "../is_slice", version = "~0" }
implements = { path = "../implements", version = "~0" }
werror = { path = "../werror", version = "~0" }
wproc_macro = { path = "../wproc_macro", version = "~0", optional = true }
# regex = "1.5.4"
# chrono = "0.4.19"
# paste = "1.0.5"
# anyhow = "1.0.48"

[dev-dependencies]
wtest_basic = { path = "../wtest_basic", version = "~0" }
trybuild = { version = "1.0.52", features = ["diff"] }
maplit = "~1.0"
anyhow = "~1.0"
rustversion = "~1.0"
# quote = { version = "~1.0" }
# proc-macro2 = { version = "~1.0" }
# syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing" ] }
