[package]
name = "wtools"
version = "0.1.7"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/wtools_lib.rs",
  "/rust/impl/meta/mod.rs",
  "/rust/impl/typing/mod.rs",
  "/rust/impl/convert/mod.rs",
  "/rust/impl/time/mod.rs",

  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtools"
path = "rust/impl/wtools_lib.rs"

[[test]]
name = "wtools_test"
path = "rust/test/wtools_test.rs"

[[example]]
name = "wtools_trivial"
path = "sample/rust/wtools_trivial/src/main.rs"

[features]
with_wtools = []
nightly = [ "typing_tools/nightly" ]
with_proc_macro = [ "wproc_macro" ]
default = [ "with_wtools" ]

[package.metadata.docs.rs]
all-features = true
# rustdoc-args = []

[dependencies]
former = { version = "~0.1", path = "../former" }
woptions = { version = "~0.1", path = "../woptions" }
# inspect_type = { version = "~0.1", path = "../inspect_type" }
# is_slice = { version = "~0.1", path = "../is_slice" }
# implements = { version = "~0.1", path = "../implements" }
meta_tools = { version = "~0.1", path = "../meta_tools" }
typing_tools = { version = "~0.1", path = "../typing_tools" }
time_tools = { version = "~0.1", path = "../time_tools" }
wstring_tools = { version = "~0.1", path = "../wstring_tools" }
werror = { version = "~0.1", path = "../werror" }
winterval = { version = "~0.1", path = "../winterval" }
wproc_macro = { version = "~0.1", path = "../wproc_macro", optional = true }
parse-display = { version = "~0.5" } # xxx : add test?
# maplit = "~1.0"
# regex = "1.5.4"
# chrono = "0.4.19"
# paste = "1.0.5"
# anyhow = "1.0.48"

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../wtest_basic" }
trybuild = { version = "~1.0", features = [ "diff" ] }
anyhow = "~1.0"
rustversion = "~1.0"
# quote = { version = "~1.0" }
# proc-macro2 = { version = "~1.0" }
# syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing" ] }
