[package]
name = "std_x"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/std_x"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/std_x"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust_alias/std_x"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/std_x_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "std_x"
path = "rust/impl/std_x_lib.rs"

[[test]]
name = "std_x_test"
path = "rust/test/std_x_lib_test.rs"

[features]
nightly = [ "wtools/nightly" ]
default = []

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
impls_index = { version = "~0.1", path = "../../rust/impls_index" } # despite impls_index is imported by wtools it should also be imported immediatly

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
