[package]
name = "derive_tools_meta"
version = "0.2.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/derive_tools_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/derive_tools_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/derive_tools_meta"
description = """
Derive to clone dyn structures.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

exclude = [ "/tests", "/examples", "-*" ]

[lib]
proc-macro = true

[features]
default = [ "enabled" ]
full = [ "enabled" ]
enabled = []

[dependencies]
macro_tools = { workspace = true, features = [ "full" ] }

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
