[package]
name = "former"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Wandalen <wanalen@01.school>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former"
# repository = "https://github.com/Wandalen/wTools/tree/master/out/rust.wtools"
# homepage = "https://github.com/Wandalen/wTools/tree/master/out/rust.wtools"
description = """
Former - variation of builder pattern.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust",
  "/Cargo.toml",
  "/Readme.md",
]

[lib]
name = "former"
#path = "../../../rust/former/mod.rs"
# path = "./module/rust/former/src/former.rs"
path = "./src/former.rs"

# [[example]]
# name = "current"
# path = "../../../rust/former/test/full.rs"

#[[test]]
#name = "former_test"
#path = "../../../rust/former/test/former.rs"

[dev-dependencies]
trybuild = { version = "1.0.52", features = ["diff"] }

[dependencies]
anyhow = "1.0.47"
maplit = "1.0.2"
#former_derive = { path = "../former_derive", version = "0.1.0" }
#former_runtime = { path = "../former_runtime", version = "0.1.0" }
