[package]
name = "former"
version = "0.1.7"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former"
description = """
Former - variation of builder pattern.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/former/former",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "former"
path = "rust/impl/former/front/lib.rs"

[[test]]
name = "former_test"
path = "rust/test/former/front_test.rs"

[[example]]
name = "former_trivial"
path = "sample/rust/former_trivial/src/main.rs"

[dependencies]
former_meta = { version = "~0.1", path = "../former_meta" }
former_runtime = { version = "~0.1", path = "../former_runtime" }

[dev-dependencies]
anyhow = "~1.0"
meta_tools = { version = "~0.1", path = "../meta_tools" }
# maplit = "~1.0"
trybuild = { version = "~1.0", features = [ "diff" ] }
wtest_basic = { version = "~0.1", path = "../wtest_basic" }
rustversion = "~1.0"
