[package]
name = "wtools"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Wandalen <wanalen@01.school>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/implements"
repository = "https://github.com/Wandalen/wTools/tree/master/out/rust.implements"
homepage = "https://github.com/Wandalen/wTools/tree/master/out/rust.implements"
description = """
A macro to answer the question: does it implement a trait
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/wtools/meta",
  "/Cargo.toml",
  "/Readme.md",
]

[lib]
name = "implements"
path = "rust/wtools/meta/mod.rs"

[[test]]
name = "wtools_test"
path = "rust/test/mod.rs"

[dependencies]
regex = "1.5.4"
chrono = "0.4.19"
paste = "1.0.5"

[[example]]
name = "trivial"
path = "sample/rust/trivial/src/main.rs"
