[package]
name = "clone_dyn"
version = "0.4.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/clone_dyn"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/clone_dyn"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/clone_dyn"
description = """
Derive to clone dyn structures.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

exclude = [ "/tests", "/examples", "-*" ]
# include = [
#   "/rust/impl/derive/clone_dyn_lib.rs",
#   "/Cargo.toml",
#   "/Readme.md",
#   "/License",
# ]

[features]

default = [ "enabled" ]
full = [ "enabled" ]
enabled = []
no_std = []
use_alloc = []

# nightly = []

# [lib]
# name = "clone_dyn"
# path = "src/derive/clone_dyn_lib.rs"
#
# [[test]]
# name = "clone_dyn_tests"
# path = "tests/derive/clone_dyn_tests.rs"
#
# [[test]]
# name = "clone_dyn_smoke_test"
# path = "tests/_integration_test/smoke_test.rs"
#
# [[example]]
# name = "clone_dyn_trivial_sample"
# path = "examples/clone_dyn_trivial_sample/src/main.rs"

[dependencies]
clone_dyn_meta = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
