[package]
name = "woptions_meta"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/woptions_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions_meta"
description = """
Mechanism to define map of options for a fuction and its defaults laconically. Its meta.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/options/meta",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
proc-macro = true
name = "woptions_meta"
path = "rust/impl/options/meta/lib.rs"

[dependencies]
proc-macro2 = "~1.0"
quote = "~1.0"
convert_case = "~0.5"
syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing", "printing" ] }
# itertools = "~0.10"
# werror = { path = "../../rust/werror", version = "~0.1" }
proc_macro_tools = { version = "~0.1", path = "../../rust/proc_macro_tools" }
meta_tools = { version = "~0.2", path = "../../rust/meta_tools" }
iter_tools = { path = "../../rust/iter_tools", version = "~0.1" }

[dev-dependencies]
trybuild = { version = "~1.0", features = [ "diff" ] }
