[package]

name = "smoke_test"
version = "0.0.1"
publish = false
edition = "2021"
description = "Smoke Test"

[dev-dependencies]
# test_tools = { workspace = true }
smoke_test = { workspace = true }
toml_edit = { version = "~0.14" }
