
checkoutLocation : "."
workspaceLocation : "./sample/rust/wtools_trivial_sample"

tasks :
  - init : |
      cargo build
      cargo run
    command : |
      cargo run

vscode :
  extensions :
    - matklad.rust-analyzer

github :
  prebuilds :
    addBadge : true
    pullRequests : true
