[package]
name = "woptions_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# woptions = "*" # qqq : xxx : uncomment later to use published version instead of local
woptions = { path = "../../../module/rust/woptions" }
