[package]

name = "former_runtime"
version = "0.1.5"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former_runtime"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
description = """
Former - variation of builder pattern. Its runtime.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/former",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "former_runtime"
path = "rust/impl/former/runtime/mod.rs"

[[test]]
name = "former_runtime_test"
path = "rust/test/former/runtime.rs"

[dev-dependencies]
wtest_basic = { path = "../wtest_basic", version = "~0" }
maplit = "~1.0.2"

[dependencies]
anyhow = "~1.0"
unzip-n = "~0.1"
