[package]
name = "former_runtime"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former_runtime"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
description = """
Former - variation of builder pattern. Its runtime macro.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/former",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "former_runtime"
path = "rust/impl/former/runtime/mod.rs"

[dev-dependencies]
trybuild = { version = "~1.0", features = ["diff"] }

[dependencies]
anyhow = "1.0.48"
# proc-macro-error = "~1.0.4"
# proc-macro2 = "~1.0.32"
# quote = "~1.0.10"
# syn = { version = "~1.0.81", features = ["full", "extra-traits", "parsing"] }
unzip-n = "~0.1.2"
