[package]
name = "wstring_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wstring_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wstring_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wstring_tools"
description = """
String tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/string",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wstring_tools"
path = "rust/impl/string/lib.rs"

[[test]]
name = "string_test"
path = "rust/test/string/test.rs"

# [[example]]
# name = "string_trivial"
# path = "sample/rust/string_trivial/src/main.rs"
# xxx

[dependencies]
former = { version = "~0.1", path = "../../rust/former" }
# wtools = { version = "~0.1", path = "../../rust/wtools" }
# werror = { version = "~0.1", path = "../../rust/werror" }

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }
