[package]
name = "type_constructor"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/type_constructor"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/type_constructor"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/type_constructor"
description = """
Fundamental data types and type constructors, like Single, Pair, Many.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/dt/type_constructor",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "type_constructor"
path = "rust/impl/dt/type_constructor/type_constructor_lib.rs"

[[test]]
name = "type_constructor_test"
path = "rust/test/dt/type_constructor/type_constructor_lib_test.rs"

[[example]]
name = "type_constructor_trivial_sample"
path = "sample/rust/type_constructor_trivial_sample/src/main.rs"

[[example]]
name = "type_constructor_derive_and_attr_sample"
path = "sample/rust/type_constructor_derive_and_attr_sample/src/main.rs"

[[example]]
name = "type_constructor_struct_sample"
path = "sample/rust/type_constructor_struct_sample/src/main.rs"

[[example]]
name = "type_constructor_parametrized_element_sample"
path = "sample/rust/type_constructor_parametrized_element_sample/src/main.rs"

[[example]]
name = "type_constructor_parametrized_tuple_sample"
path = "sample/rust/type_constructor_parametrized_tuple_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
