[package]
name = "graphs_tools"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/graphs_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/graphs_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/graphs_tools"
description = """
Graphs tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/graph",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [
  "use_std",
  "cell_factory",
]
full = [
  "use_std",
  "cell_factory",
]
cell_factory = []
use_std = []
use_alloc = []

[lib]
name = "graphs_tools"
path = "rust/impl/graph/graphs_tools_lib.rs"

[[test]]
name = "graphs_tools_test"
path = "rust/test/graph/graphs_tools_lib_test.rs"

[[test]]
name = "graphs_tools_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "graphs_tools_trivial_sample"
# path = "sample/rust/graphs_tools_trivial_sample/src/main.rs"

[dependencies]
indexmap = "~1.8"
wtools = { version = "~0.2", path = "../../rust/wtools", features = [ "full" ] }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
