[package]
name = "inspect_type"
version = "0.0.8"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/inspect_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/inspect_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/inspect_type"
description = """
Diagnostic-purpose tools to inspect type of a variable and its size.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "diagnostic-purpose" ]

include = [
  "/rust/impl/meta/inspect_type.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "inspect_type"
path = "rust/impl/meta/inspect_type.rs"

[[test]]
name = "inspect_type_test"
path = "rust/test/meta/inspect_type_test.rs"

[dependencies]

[dev-dependencies]
wtest_basic = { path = "../wtest_basic", version = "~0" }

[[example]]
name = "trivial"
path = "sample/rust/inspect_type_trivial/src/main.rs"
