[package]
name = "fundamental_data_type"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/fundamental_data_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/fundamental_data_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/fundamental_data_type"
description = """
Fundamental data types and type constructors, like Single, Pair, Many.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/dt/type_constructor/fundamental_data_type_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "fundamental_data_type"
path = "rust/impl/dt/type_constructor/fundamental_data_type_lib.rs"

[[test]]
name = "fundamental_data_type_test"
path = "rust/test/dt/type_constructor/fundamental_data_type_lib_test.rs"

# [[example]]
# name = "fundamental_data_type_trivial_sample"
# path = "sample/rust/type_constructor_trivial_sample/src/main.rs"
#
# [[example]]
# name = "fundamental_data_type_derive_and_attr_sample"
# path = "sample/rust/type_constructor_derive_and_attr_sample/src/main.rs"
#
# [[example]]
# name = "fundamental_data_type_struct_sample"
# path = "sample/rust/type_constructor_struct_sample/src/main.rs"
#
# [[example]]
# name = "fundamental_data_type_parametrized_element_sample"
# path = "sample/rust/type_constructor_parametrized_element_sample/src/main.rs"
#
# [[example]]
# name = "fundamental_data_type_parametrized_tuple_sample"
# path = "sample/rust/type_constructor_parametrized_tuple_sample/src/main.rs"
#
# xxx

[dependencies]
type_constructor = { version = "~0.1", path = "../../rust/type_constructor" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# trybuild = { version = "~1.0", features = [ "diff" ] }
