[package]
name = "wcommandsaggregator"
version = "0.0.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wcommandsaggregator"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wcommandsaggregator"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wcommandsaggregator"
description = """
The tool to make CLI ( commands user interface ). It is able to aggregate external binary applications, as well as functions, which are written in your language.
"""
categories = [ "command-line-interface" ]
keywords = [ "cli", "general-purpose" ]

include = [
  "/rust/impl/commandsaggregator/mod.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wcommandsaggregator"
path = "rust/impl/commandsaggregator/mod.rs"

[[test]]
name = "wcommandsaggregator_test"
path = "rust/test/commandsaggregator/commandsaggregator.rs"

# [[example]]
# name = "trivial"
# path = "sample/rust/wtest_trivial/src/main.rs"

# [dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }

# [dependencies]
# paste = "~1.0"
# anyhow = "~1.0"
# wtest_basic = { path = "../wtest_basic", version = "~0" }
