[package]
name = "___"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/___"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
description = """
Macro to answer the question: is it a slice?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/sketch",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "___"
path = "rust/impl/sketch/lib.rs"

[[test]]
name = "____test"
path = "rust/test/sketch/test.rs"

# [[example]]
# name = "____trivial"
# path = "sample/rust/____trivial/src/main.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }
wtest_basic = { version = "~0.1", path = "../wtest_basic" }
