[package]
name = "wstring_tools_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# wstring_tools = "*" # qqq : xxx : uncomment later to use published version instead of local
wstring_tools = { path = "../../../module/rust/wstring_tools" }
