[package]
name = "winterval"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/winterval"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/winterval"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/winterval"
description = """
Interval adapter for both open/closed implementations of intervals ( ranges ).
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/dt/interval_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "winterval"
path = "rust/impl/dt/interval_lib.rs"

[[test]]
name = "interval_test"
path = "rust/test/dt/interval_tests.rs"

[[test]]
name = "winterval_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "winterval_trivial"
path = "sample/rust/winterval_trivial/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }

# xxx : move into dt?
