[package]
name = "former_runtime"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Wandalen <wanalen@01.school>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
description = """
Former - variation of builder pattern. Its runtime.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/former/runtime",
  "/Cargo.toml",
  "/Readme.md",
]

[lib]
name = "former_runtime"
path = "/rust/former/runtime/mod.rs"

[[test]]
name = "derive_runtime_test"
path = "/rust/former/test/runtime.rs"

[dev-dependencies]
trybuild = { version = "1.0.52", features = ["diff"] }
maplit = "1.0.2"

[dependencies]
anyhow = "1.0.47"
