[package]
name = "wca2"
version = "0.1.0"
edition = "2021"
authors = ["Kostiantyn Wandalen <wandalen@obox.systems>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wca"
repository = "https://github.com/Wandalen/wTools/tree/master/module/move/wca"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/move/wca/Readme.md"
description = """
The tool to make CLI ( commands user interface ). It is able to aggregate external binary applications, as well as functions, which are written in your language.
"""
categories = [ "command-line-interface", "command-line-utilities" ]
keywords = [ "wtools", "CLI", "CUI", "user-interface" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/ca2",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]
use_std = [ "default_handlers" ]
use_alloc = []

default_handlers = [
  "on_error_default",
  "on_syntax_error_default",
  "on_ambiguity_default",
  "on_unknown_command_error_default",
  "on_get_help_default",
  "on_print_commands_default",
]

on_error_default = []
on_syntax_error_default = []
on_ambiguity_default = []
on_unknown_command_error_default = []
on_get_help_default = []
on_print_commands_default = []

[lib]
name = "wca2"
path = "rust/impl/ca2/wca_lib.rs"

[[test]]
name = "wca2_test"
path = "rust/test/ca2/wca_tests.rs"

[[test]]
name = "wca2_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "wca2_trivial_sample"
# path = "sample/rust/wca2_trivial_sample/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
former = { version = "~0.1", path = "../../rust/former" }
anymap = "0.12"
log = "0.4"
nom = "7.1"

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
