[package]
name = "strs_tools_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[features]
# use_std = []
no_std = []
split = []
default = [ "split" ]

[dependencies]
strs_tools = { workspace = true }
