[package]
name = "sqlx_query"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Viktor Dudnik <viktor.d@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/sqlx_query"
repository = "https://github.com/Wandalen/wTools/tree/master/module/move/sqlx_query"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/move/sqlx_query"
description = """
Expands to either sqlx function `query` or macro `query!` call depending on `sqlx_compiletime_checks` has been enabled during the build.
"""

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
exclude = [ "/tests", "/examples", "-*" ]

include = [
  "/rust/impl/sqlx_query",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = []
use_alloc = []
enabled = []

default_handlers = [
  "on_error_default",
  "on_syntax_error_default",
  "on_ambiguity_default",
  "on_unknown_command_error_default",
  "on_get_help_default",
  "on_print_commands_default",
]

on_error_default = [ "enabled" ]
on_syntax_error_default = [ "enabled" ]
on_ambiguity_default = [ "enabled" ]
on_unknown_command_error_default = [ "enabled" ]
on_get_help_default = [ "enabled" ]
on_print_commands_default = [ "enabled" ]

[dependencies]

[dev-dependencies]
test_tools = { workspace = true }