[package]
name = "proc_macro_tools"
version = "0.1.18"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/proc_macro_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/proc_macro_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/proc_macro_tools"
description = """
Tools for writing procedural macroses.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/proc_macro",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "proc_macro_tools"
path = "src/proc_macro/proc_macro_tools_lib.rs"

[[test]]
name = "proc_macro_tools_test"
path = "tests/proc_macro/proc_macro_tools_tests.rs"

[[test]]
name = "proc_macro_tools_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "proc_macro_tools_trivial_sample"
path = "examples/proc_macro_tools_trivial_sample/src/main.rs"

[dependencies]
proc-macro2 = { version = "~1.0", features = [] }
quote = { version = "~1.0", features = [] }
syn = { version = "~1.0", features = [ "full", "extra-traits" ] }
winterval = { workspace = true, features = [ "default" ] }
# xxx : rid off winterval, maybe?
type_constructor = { workspace = true, features = [ "default" ] }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
test_tools = { workspace = true }
