[package]
name = "is_slice"
version = "0.0.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/implements"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/implements"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/implements"
description = """
Macro to answer the question: is it a slice?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/wtools/meta/implements",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "implements"
path = "rust/impl/meta/implements/mod.rs"

[[test]]
name = "implements_test"
path = "rust/test/meta/implements_test.rs"

[dependencies]
# regex = "1.5.4"
# chrono = "0.4.19"
# paste = "1.0.5"

[[example]]
name = "trivial"
path = "sample/rust/implements_trivial/src/main.rs"
