[package]
name = "is_slice"
version = "0.0.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/is_slice"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/is_slice"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/is_slice"
description = """
Macro to answer the question: is it a slice?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/meta/is_slice.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "is_slice"
path = "rust/impl/meta/is_slice.rs"

[[test]]
name = "is_slice_test"
path = "rust/test/meta/is_slice_test.rs"

# [[example]]
# name = "trivial"
# path = "sample/rust/is_slice_trivial/src/main.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }
wtest = { path = "../wtest", version = "~0" }
