[package]
name = "werror_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[features]
use_std = []
default = [ "use_std" ]

[dependencies]
werror = { version = "*", path = "../../../module/rust/werror" }
