[package]
name = "wlang"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wlang"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wlang"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wlang"
description = """
Wlang.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "wlang"
path = "rust/impl/_blank/standard_lib.rs"

[[test]]
name = "wlang_test"
path = "rust/test/_blank/lib_test.rs"

[[test]]
name = "wlang_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "wlang_trivial_sample"
# path = "sample/rust/wlang_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
