[package]
name = "instance_of"
version = "0.0.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/instance_of"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/instance_of"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/instance_of"
description = """
Macro to answer the question: does it implement a trait?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/meta/implements.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "instance_of"
path = "rust/impl/meta/implements.rs"

[[test]]
name = "instance_of_test"
path = "rust/test/meta/implements.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = ["diff"] }
wtest = { path = "../wtest", version = "~0" }

[[example]]
name = "trivial"
path = "sample/rust/meta_implements_trivial/src/main.rs"
