[package]
name = "wproc_macro"
version = "0.0.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wproc_macro"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wproc_macro"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wproc_macro"
description = """
Tools for writing procedural macroses.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/proc_macro",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wproc_macro"
path = "rust/impl/proc_macro/mod.rs"

[[test]]
name = "wproc_macro"
path = "rust/test/proc_macro/mod.rs"

[[example]]
name = "trivial"
path = "sample/rust/wproc_macro_trivial/src/main.rs"

[dependencies]
proc-macro2 = { version = "~1.0.32", features = [ "span-locations" ] }
quote = "~1.0.10"
syn = { version = "~1.0.81", features = [ "full", "extra-traits", "parsing" ] }
# werror = { path = "../werror", version = "~0.0" }

[dev-dependencies]
trybuild = { version = "~1.0", features = ["diff"] }
wtest_basic = { path = "../wtest_basic", version = "~0" }
