[package]
name = "wproc_macro"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wproc_macro"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wproc_macro"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wproc_macro"
description = """
Tools for writing procedural macroses.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/proc_macro",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wproc_macro"
path = "rust/impl/proc_macro/lib.rs"

[[test]]
name = "proc_macro"
path = "rust/test/proc_macro/lib_test.rs"

[[example]]
name = "proc_macro_trivial"
path = "sample/rust/proc_macro_trivial/src/main.rs"

[dependencies]
proc-macro2 = { version = "~1.0" }
syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing" ] }
winterval = { version = "~0.1", path = "../winterval" }
# inspect_type = { version = "~0.1", path = "../inspect_type" }
# werror = { path = "../werror", version = "~0.1" }

[dev-dependencies]
trybuild = { version = "~1.0", features = ["diff"] }
wtest_basic = { version = "~0.1", path = "../wtest_basic" }
quote = "~1.0"
