[package]
name = "fundamental_data_type_derive_and_attr_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
fundamental_data_type = { version = "*", path = "../../../module/rust/fundamental_data_type" }
