name : wtools

on : push

env :
  CARGO_TERM_COLOR : always
  THE_MODULE : wtools

jobs :

  # wtools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/wtools/Cargo.toml'
      module_name : 'wtools'

  # wTools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust_alias/wTools/Cargo.toml'
      module_name : 'wTools'

  # std_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust_alias/std_tools/Cargo.toml'
      module_name : 'std_tools'

  # std_x

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust_alias/std_x/Cargo.toml'
      module_name : 'std_x'

  # non_std

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust_alias/non_std/Cargo.toml'
      module_name : 'non_std'
