name: meta_tools

on : push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if : "startsWith( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses: Wandalen/wTools/.github/workflows/RustFull.yml@master
    with:
      manifest_path: 'module/rust/meta_tools/Cargo.toml'

  build_fast:
    if : "!startsWith( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'meta_tools' )"
    uses: Wandalen/wTools/.github/workflows/RustFast.yml@master
    with:
      manifest_path: 'module/rust/meta_tools/Cargo.toml'

