name : implements

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # implements

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/implements/Cargo.toml'
      module_name : 'implements'

  # instance_of

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust_alias/instance_of/Cargo.toml'
      module_name : 'instance_of'
