name : wplot

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wplot

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/move/wplot/Cargo.toml'
      module_name : 'wplot'
      commit_message : ${{ github.event.head_commit.message }}

  # plot_interface

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/move/plot_interface/Cargo.toml'
      module_name : 'plot_interface'
      commit_message : ${{ github.event.head_commit.message }}
