name : woptions

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # woptions

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/woptions/Cargo.toml'
      module_name : 'woptions'

  # woptions_meta

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/woptions_meta/Cargo.toml'
      module_name : 'woptions_meta'

  # woptions_runtime

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/woptions_runtime/Cargo.toml'
      module_name : 'woptions_runtime'
