name : wautomata

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wautomata

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/wautomata/Cargo.toml'
      module_name : 'wautomata'
