name : proc_macro_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # proc_macro_tools

  build :
    if : "contains( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses : Wandalen/wTools/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/rust/proc_macro_tools/Cargo.toml'

  build_fast :
    if : "!contains( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'proc_macro_tools' )"
    uses : Wandalen/wTools/.github/workflows/RustFast.yml@master
    with :
      manifest_path : 'module/rust/proc_macro_tools/Cargo.toml'

  # wproc_macro

  build_wproc_macro :
    if : "contains( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses : Wandalen/wTools/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/rust/wproc_macro/Cargo.toml'

  build_fast_wproc_macro :
    if : "!contains( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'proc_macro_tools' )"
    uses : Wandalen/wTools/.github/workflows/RustFast.yml@master
    with :
      manifest_path : 'module/rust/wproc_macro/Cargo.toml'

  # macro_tools

  build_macro_tools :
    if : "contains( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses : Wandalen/wTools/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/rust/macro_tools/Cargo.toml'

  build_fast_macro_tools :
    if : "!contains( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'proc_macro_tools' )"
    uses : Wandalen/wTools/.github/workflows/RustFast.yml@master
    with :
      manifest_path : 'module/rust/macro_tools/Cargo.toml'
