
name: rust

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
    if : "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install latest stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test

