[package]
name = "diagnostics_tools"
version = "0.1.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/diagnostics_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/diagnostics_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/diagnostics_tools"
description = """
Diagnostics tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

exclude = [ "/tests", "/examples", "-*" ]
# include = [
#   "/rust/impl/diagnostics",
#   "/Cargo.toml",
#   "/Readme.md",
#   "/License",
# ]

[features]
default = [
  "enabled",
  "runtime_assertions",
  "compiletime_assertions",
  # "use_std"
]
full = [
  "enabled",
  "runtime_assertions",
  "compiletime_assertions",
  # "use_std",
  # "use_alloc"
]
# use_std = []
no_std = []
use_alloc = []
enabled = []

runtime_assertions = [ "pretty_assertions" ] # run-time assertions
compiletime_assertions = [] # compile-time assertions

[dependencies]
pretty_assertions = { version = "~1.2", optional = true }

[dev-dependencies]
test_tools = { workspace = true }
# smoke_test = { workspace = true }
