[package]
name = "____alias"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/___"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/___"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/sketch_alias",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "sketch_alias"
path = "rust/impl/sketch_alias/lib.rs"

[[test]]
name = "sketch_alias_test"
path = "rust/test/sketch_blank/lib_test.rs"

[dependencies]

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }
